const PROJECT_ID="stylemateai-d5843";
export function bearer(header="") { return header.startsWith("Bearer ")?header.slice(7).trim():""; }
export async function verifyFirebaseToken(token,apiKey) { if(!apiKey)throw new Error("FIREBASE_WEB_API_KEY is not configured."); const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(apiKey)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idToken:token})}); if(!response.ok)return null; return (await response.json()).users?.[0]||null; }
function decode(value){if(!value)return null;if("stringValue"in value)return value.stringValue;if("integerValue"in value)return Number(value.integerValue);if("doubleValue"in value)return Number(value.doubleValue);if("booleanValue"in value)return value.booleanValue;if("timestampValue"in value)return value.timestampValue;if("nullValue"in value)return null;if("arrayValue"in value)return (value.arrayValue.values||[]).map(decode);if("mapValue"in value)return decodeFields(value.mapValue.fields||{});return null}
function decodeFields(fields={}){return Object.fromEntries(Object.entries(fields).map(([key,value])=>[key,decode(value)]))}
export async function getUserProfile(token,uid,projectId=PROJECT_ID){const response=await fetch(`https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents/users/${encodeURIComponent(uid)}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error("Could not verify the user profile.");return decodeFields((await response.json()).fields||{})}
export async function getOwnedWardrobe(token,uid,projectId=PROJECT_ID){const response=await fetch(`https://firestore.googleapis.com/v1/projects/${projectId}/databases/(default)/documents:runQuery`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({structuredQuery:{from:[{collectionId:"wardrobe"}],where:{fieldFilter:{field:{fieldPath:"userId"},op:"EQUAL",value:{stringValue:uid}}},limit:150}})});if(!response.ok)throw new Error("Could not read the authenticated wardrobe.");const rows=await response.json();return rows.filter((row)=>row.document).map((row)=>({id:row.document.name.split("/").pop(),...decodeFields(row.document.fields||{})}))}
export function isPremiumProfile(profile={}){return profile.subscription?.plan==="premium"&&Number(profile.subscription?.premiumUntil)>Date.now()}
export async function logApiCall(token,payload){try{await fetch("https://us-central1-stylemateai-d5843.cloudfunctions.net/logApiCall",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({data:payload})})}catch{}}
export function json(body,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}})}
export function clean(value,max=160){return String(value??"").replace(/[<>]/g,"").trim().slice(0,max)}
